version: '3.9'

services:
  database:
    image: postgres:15
    container_name: auth_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JavaMTS
      POSTGRES_DB: auth_service
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service_app
    environment:
      DB_URL: jdbc:postgresql://database:5432/auth_service
      DB_USERNAME: postgres
      DB_PASSWORD: JavaMTS
    depends_on:
      - database
    ports:
      - "8080:8080"

volumes:
  db_data:
